"""empty message

Revision ID: 41d4cf378886
Revises: d8834a0e851b
Create Date: 2024-04-27 14:21:02.019748

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '41d4cf378886'
down_revision = 'd8834a0e851b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_user',
    sa.Column('id_user', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('fone', sa.String(length=11), nullable=True),
    sa.Column('gender', sa.Enum('1', '2'), nullable=True),
    sa.Column('date_birth', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('tb_usuario', schema=None) as batch_op:
        batch_op.drop_index('email')

    op.drop_table('tb_usuario')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_usuario',
    sa.Column('id_user', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('fone', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('gender', mysql.ENUM('1', '2'), nullable=True),
    sa.Column('date_birth', sa.DATE(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_user'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('tb_usuario', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=True)

    op.drop_table('tb_user')
    # ### end Alembic commands ###
