"""empty message

Revision ID: d8834a0e851b
Revises: 
Create Date: 2024-04-27 14:11:34.302469

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd8834a0e851b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_usuario',
    sa.Column('id_user', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('fone', sa.String(length=11), nullable=True),
    sa.Column('gender', sa.Enum('1', '2'), nullable=True),
    sa.Column('date_birth', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('tb_users', schema=None) as batch_op:
        batch_op.drop_index('id_usuario_UNIQUE')

    op.drop_table('tb_users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_users',
    sa.Column('id_user', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('fone', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('gender', mysql.ENUM('1', '2'), nullable=True),
    sa.Column('date_birth', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('is_admin', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    sa.Column('is_client', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_user'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('tb_users', schema=None) as batch_op:
        batch_op.create_index('id_usuario_UNIQUE', ['id_user'], unique=True)

    op.drop_table('tb_usuario')
    # ### end Alembic commands ###
